network:
  version: 2
  renderer: networkd
  ethernets:
    enp2s0:
      dhcp4: no
      addresses: [10.0.17.247/16]
      gateway4:  10.0.17.1
      nameservers:
        addresses: [202.96.134.133, 114.114.114.114]