       
sc  stop AJRouter              
sc  stop ALG           
sc  stop AppIDSvc              
sc  stop Appinfo           
sc  stop AppMgmt           
sc  stop AppReadiness              
sc  stop AppVClient            
sc  stop wsappx           
sc  stop AppXSvc           
sc  stop AudioEndpointBuilder              
sc  stop Audiosrv              
sc  stop AxInstSV              
sc  stop BDESVC            
sc  stop BFE           
sc  stop BITS              
sc  stop BrokerInfrastructure              
sc  stop Browser           
sc  stop BthHFSrv              
sc  stop bthserv           
sc  stop CDPSvc            
sc  stop CertPropSvc           
sc  stop ClipSVC           
sc  stop COMSysApp             
sc  stop CoreMessagingRegistrar            
sc  stop CryptSvc              
sc  stop CscService            
sc  stop DcomLaunch            
sc  stop DcpSvc            
sc  stop defragsvc             
sc  stop DeviceAssociationService              
sc  stop DeviceInstall             
sc  stop DevQueryBroker            
sc  stop DFServ            
sc  stop Dhcp              
sc  stop diagnosticshub.standardcollector.service              
sc  stop DiagTrack             
sc  stop DmEnrollmentSvc           
sc  stop dmwappushservice              
sc  stop Dnscache              
sc  stop DoSvc             
sc  stop dot3svc           
sc  stop DPS           
sc  stop DsmSvc            
sc  stop DsSvc             
sc  stop EapHost           
sc  stop EFS           
sc  stop embeddedmode              
sc  stop EntAppSvc             
sc  stop EventLog              
sc  stop EventSystem           
sc  stop Fax           
sc  stop fdPHost           
sc  stop FDResPub              
sc  stop fhsvc             
sc  stop FontCache             
sc  stop FrameServer           
sc  stop FRClient              
sc  stop gpsvc             
sc  stop hidserv           
sc  stop HomeGroupListener             
sc  stop HomeGroupProvider             
sc  stop HvHost            
sc  stop icssvc            
sc  stop IKEEXT            
sc  stop iphlpsvc              
sc  stop irmon             
sc  stop KeyIso            
sc  stop KtmRm             
sc  stop LanmanServer              
sc  stop LanmanWorkstation             
sc  stop lfsvc             
sc  stop LicenseManager            
sc  stop lltdsvc           
sc  stop lmhosts           
sc  stop LSM           
sc  stop MapsBroker            
sc  stop MpsSvc            
sc  stop MSDTC             
sc  stop MSiSCSI           
sc  stop msiserver             
sc  stop NcaSvc            
sc  stop NcbService            
sc  stop NcdAutoSetup              
sc  stop Netlogon              
sc  stop Netman            
sc  stop netprofm              
sc  stop NetSetupSvc           
sc  stop NetTcpPortSharing             
sc  stop NgcCtnrSvc            
sc  stop NgcSvc            
sc  stop NlaSvc            
sc  stop nsi           
sc  stop p2pimsvc              
sc  stop p2psvc            
sc  stop PcaSvc            
sc  stop PeerDistSvc           
sc  stop PerfHost              
sc  stop PhoneSvc              
sc  stop pla           
sc  stop PlugPlay              
sc  stop PNRPAutoReg           
sc  stop PNRPsvc           
sc  stop PolicyAgent           
sc  stop Power             
sc  stop PrintNotify           
sc  stop ProfSvc           
sc  stop QWAVE             
sc  stop RasAuto           
sc  stop RasMan            
sc  stop RemoteAccess              
sc  stop RemoteRegistry            
sc  stop RetailDemo            
sc  stop RmSvc             
sc  stop RpcEptMapper              
sc  stop RpcLocator            
sc  stop RpcSs             
sc  stop SamSs             
sc  stop SCardSvr              
sc  stop ScDeviceEnum              
sc  stop Schedule              
sc  stop SCPolicySvc           
sc  stop SDRSVC            
sc  stop seclogon              
sc  stop SENS              
sc  stop Sense             
sc  stop SensorDataService             
sc  stop SensorService             
sc  stop SensrSvc              
sc  stop SessionEnv            
sc  stop SharedAccess              
sc  stop ShellHWDetection              
sc  stop shpamsvc              
sc  stop smphost           
sc  stop SmsRouter             
sc  stop SNMPTRAP              
sc  stop Spooler           
sc  stop sppsvc            
sc  stop SSDPSRV           
sc  stop SstpSvc           
sc  stop StateRepository           
sc  stop stisvc            
sc  stop StorSvc           
sc  stop svsvc             
sc  stop swprv             
sc  stop SysMain           
sc  stop SystemEventsBroker            
sc  stop TabletInputService            
sc  stop TapiSrv           
sc  stop TermService           
sc  stop Themes            
sc  stop TieringEngineService              
sc  stop tiledatamodelsvc              
sc  stop TimeBrokerSvc             
sc  stop TrkWks            
sc  stop TrustedInstaller              
sc  stop tzautoupdate              
sc  stop UevAgentService           
sc  stop UI0Detect             
sc  stop UmRdpService              
sc  stop upnphost              
sc  stop UserManager           
sc  stop UsoSvc            
sc  stop VaultSvc              
sc  stop vds           
sc  stop vmicguestinterface            
sc  stop vmicheartbeat             
sc  stop vmickvpexchange           
sc  stop vmicrdv           
sc  stop vmicshutdown              
sc  stop vmictimesync              
sc  stop vmicvmsession             
sc  stop vmicvss           
sc  stop VSS           
sc  stop W32Time           
sc  stop WalletService             
sc  stop wbengine              
sc  stop WbioSrvc              
sc  stop Wcmsvc            
sc  stop wcncsvc           
sc  stop WdiServiceHost            
sc  stop WdiSystemHost             
sc  stop WdNisSvc              
sc  stop WebClient             
sc  stop Wecsvc            
sc  stop WEPHOSTSVC            
sc  stop wercplsupport             
sc  stop WerSvc            
sc  stop WiaRpc            
sc  stop WinDefend             
sc  stop WinHttpAutoProxySvc           
sc  stop Winmgmt           
sc  stop WinRM             
sc  stop wisvc             
sc  stop WlanSvc           
sc  stop wlidsvc           
sc  stop wmiApSrv              
sc  stop WMPNetworkSvc             
sc  stop workfolderssvc            
sc  stop WPDBusEnum            
sc  stop WpnService            
sc  stop wscsvc            
sc  stop WSearch           
sc  stop wuauserv              
sc  stop wudfsvc           
sc  stop WwanSvc           
sc  stop XblAuthManager            
sc  stop XblGameSave           
sc  stop XboxNetApiSvc             

@pause                 
