code --install-extension 766b.go-outliner
code --install-extension aaron-bond.better-comments
code --install-extension adpyke.vscode-sql-formatter
code --install-extension AlanWalk.markdown-toc
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension Compulim.compulim-vscode-closetag
code --install-extension dawhite.mustache
code --install-extension dbaeumer.vscode-eslint
code --install-extension EditorConfig.EditorConfig
code --install-extension emeraldwalk.RunOnSave
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension felixfbecker.php-pack
code --install-extension formulahendry.auto-close-tag
code --install-extension fterrag.vscode-php-cs-fixer
code --install-extension HookyQR.beautify
code --install-extension ikappas.composer
code --install-extension itmcdev.generic-extension-pack
code --install-extension itmcdev.php-extension-pack
code --install-extension liximomo.sftp
code --install-extension MS-CEINTL.vscode-language-pack-zh-hans
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.sublime-keybindings
code --install-extension neilbrayfield.php-docblocker
code --install-extension octref.vetur
code --install-extension onecentlin.phpunit-snippets
code --install-extension secanis.jenkinsfile-support
code --install-extension Shan.code-settings-sync
code --install-extension yzhang.markdown-all-in-one
pause